export const blogList = [
  {
    id: 1,
    title: "7 CSS tools you should be using ",
    category: "development",
    subCategory: ["frontend", "ui/ux", "design"],
    description:
      "CSS is getting more and more complicated to write. Thankfully, there are tools that make the task of authoring CSS a little bit easier. From identifying errors in your stylesheets to presenting useful stats about your code, these online tools will undoubtedly help during CSS development.",
    authorName: "William Craig",
    authorAvatar: "/assets/images/author1.jpg",
    createdAt: "July 19, 2021",
    cover: "/assets/images/designer-2.jpg",
  },
  {
    id: 2,
    title: "Milan Places That Highlight The City",
    category: "travel",
    subCategory: ["vacation", "holidays", "sight seeing"],
    description:
      "Milan, the fashion capital of Italy, is a city that seamlessly blends tradition and innovation. From the iconic Duomo to the trendy Brera district, Milan is a treasure trove of art, architecture, and culture. In this article, we'll take you on a journey through the city's most iconic landmarks, hidden gems, and off-the-beaten-path destinations. Whether you're interested in history, art, fashion, or food, Milan has something for everyone. So, come and discover the city's unique charm and character.",
    authorName: "Tim Parks",
    authorAvatar: "/assets/images/author-2.jpg",
    createdAt: "August 25, 2002",
    cover: "/assets/images/milan-1.jpg",
  },
  {
    id: 3,
    title:
      "Shopping for fun or shopping to buy: Is it different online and offline?",
    category: "shopping",
    subCategory: ["e-commerce store", "clothing", "shopping store"],
    description:
      "Consumers can shop both online and offline, either for fun or for needs. We investigate the consequences of shopping for fun or for need on word-of-mouth (WOM), intentional loyalty, and price consciousness directly comparing the offline and online settings. We find differences in the relationships among the considered variables, with the offline context being characterized by a simplified structure of causalities, greater maturity, and fewer but stronger ties among the considered constructs, compared with the online context. Furthermore, the content of WOM changes: consumers share experiential issues when they shop for fun, and efficiency issues when their shopping is goal-oriented.",
    authorName: "Gabriele Pizzi",
    authorAvatar: "/assets/images/author-3.jpg",
    createdAt: "May 01, 2014",
    cover: "/assets/images/shopping-2.jpg",
  },
  {
    id: 4,
    title: "ADVENTURE IN YOU",
    category: "adventure",
    subCategory: ["adrenaline", "stay-fit", "lifestyle"],
    description:
      "Hey there! We’re Tom and Anna, the two travelers behind this (kickass travel blog). Let me fill you in on a secret. Traveling has changed our lives and we want it to do the same for you. We’ve been traveling the world for the last 9 years, living in 5 different continents. We are experts in outdoor travel, destination advice, gear, entrepreneurship, and blogging! Our advice in these areas have been featured in various publications like Foundr, Business Insider, Forbes, Elite Daily and more. This blog has been read by over 13 million people over the last few years. Before we started this travel blog, we found ourselves asking questions like this: 1. “What’s the best way to start planning a trip?” 2. “How do I find the best things to do while on the road?” 3. “How can some people afford to travel for so long?” 4. “How do people make money from travel blogging?” You see, before we became full-time travel bloggers, we were just like most people. We knew we wanted more out of life but we just didn’t know how to change things. I, Anna was working in the Philippines as a teacher and Tom was working in the UK as a waiter while finishing his degree in Aerospace Engineering.",
    authorName: "Anna and Tom Rogers",
    authorAvatar: "/assets/images/author-4.jpg",
    createdAt: "September 16, 2016",
    cover: "/assets/images/graphic-design-trends-2.png",
  },
  {
    id: 5,
    title: "Loaded BBQ Baked Potatoes",
    category: "cooking",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "My husband has been on a potato binge as of recently. I'm not complaining one bit, especially because it's been fun experimenting with new recipes to keep things fresh and exciting in the kitchen. The other day he asked me how to BBQ potatoes so we came up with this, Loaded BBQ Potatoes.Welcome to What's Gaby Cooking! I'm Gaby! I'm a culinary school trained chef, New York Times Best Selling cookbook author, entrepreneur, and mom and I’m here to bring you easy, healthy, comforting recipes that you and your friends and family will love!",
    authorName: "Gaby Dalkin",
    authorAvatar: "/assets/images/author-5.jpg",
    createdAt: "August 17, 2017",
    cover: "/assets/images/make-it-personal-2.jpg",
  },
  {
    id: 6,
    title: "Beyond the Beach",
    category: "travel",
    subCategory: ["beaches", "sea", "holidays"],
    description:
      "After finding out she was pregnant, Deidre Esposito laid out her jewelry and wallet on her dresser and leaped head first from her third-floor dorm window. Ruling out murder, Blacksburg Detective Benny Fidalgo seeks to find out why but his police chief, uninterested in getting behind an obvious suicide, reassigns him to chasing car thieves. Defying the chief, Fidalgo finds himself pitted against Deidre’s private eye uncle who is out to find the guy who wronged his niece. Aware that she hadn’t been dating, Fidalgo discovers that the young woman had won a campus contest and a trip to a Caribbean resort. Believing it relevant, he travels there and identifies the individual Deidre hooked up with but not before the uncle had already done so. In the end, after five murders, Fidalgo learns the awful truth…that the college senior took her life to extinguish the devil’s lascivious sneer in the nightmare of nightmares.",
    authorName: "Tim Connolly",
    authorAvatar: "/assets/images/author-19.jpg",
    createdAt: "November 13, 2023",
    cover: "/assets/images/beach-1.jpg",
  },
  {
    id: 7,
    title: "Art, Perception, and Reality",
    category: "art",
    subCategory: ["skill", "design", "passion"],
    description:
      "In Art, Perception, and Reality three eminent scholars explore questions relating to the nature of representation in art. Art historian E. H. Gombrich asks how we recognize likeness—in portraits or caricatures for instance—and concludes that we do so by empathy. Psychologist Julian Hochberg rejects Gombrich's argument, suggesting instead that the expectations aroused in the scanning processes of visual perception account for recognition of likeness. Finally, philosopher Max black argues that no criteria have been established for defining conditions of representation and concludes that representation is a cluster concept.",
    authorName: " E. H. Gombrich, Julian Hochberg, Max Black",
    authorAvatar: "/assets/images/author-19.jpg",
    createdAt: "January 09, 1973",
    cover: "/assets/images/art-2.jpg",
  },
  {
    id: 8,
    title: 'The Symphony of Change Tracing the Evolution of Music Genres',
    category: 'music',
    subCategory: ['history', 'genres', 'culture'],
    description:
      "Music, an ever-evolving art form, mirrors the cultural, social, and technological shifts of its time. This blog post delves into the evolution of various music genres, exploring their origins, transformations, and how these styles have been integrated into the curriculum of music education institutions like the Musicians Institute. Understanding the evolution of these genres not only enriches one’s musical knowledge but also enhances appreciation and creativity.",
    authorName: 'Musicians Institute (MI)',
    authorAvatar: "/assets/images/author-8.jpg",
    createdAt: "January 24, 2024 ",
    cover: "/assets/images/music-2.jpg",
  },
  {
    id: 9,
    title:
      "Kate Tellier: Championing the rise of women’s sport by embracing its distinct value proposition",
    category: "sport",
    subCategory: ["athletes", "empowerment", "fitness"],
    description:
      "Kate Tellier, student at the Johan Cruyff Institute Amsterdam, believes in the unique value proposition of women’s sport to drive commercial success and societal impact. Female athletes are increasingly recognized not just for their sporting achievements but also for their role in driving social change, contributing to the appeal and commercial viability of women’s sport",
    authorName: "Kate Tellier",
    authorAvatar: "/assets/images/author-17.jpg",
    createdAt: "May 30, 2024",
    cover: "/assets/images/sport-2.jpg",
  },
  {
    id: 10,
    title: "YOU ARE THE ADVENTURE!",
    category: "adventure",
    subCategory: ["adrenaline", "stay-fit", "lifestyle"],
    description:
      "You Are The Adventure! by J. Allen Boone is a self-help book that aims to inspire readers to embrace life as an adventure. The author argues that life is full of opportunities for growth, learning, and personal development, and that we should approach each day with a sense of curiosity and excitement.The book is divided into short, easy-to-read chapters that cover a wide range of topics, including meditation, visualization, positive thinking, and goal-setting. The author uses anecdotes and personal stories to illustrate his points, and provides practical exercises and tips for readers to try out.Throughout the book, the author encourages readers to take risks, face their fears, and embrace new challenges. He argues that by doing so, we can discover our true potential and live a more fulfilling life.You Are The Adventure! is a motivational and uplifting book that is suitable for anyone looking to live a more adventurous and fulfilling life. Whether you are struggling with self-doubt, feeling stuck in a rut, or simply looking for inspiration, this book offers practical advice and encouragement to help you take the next step.This scarce antiquarian book is a facsimile reprint of the old original and may contain some imperfections such as library marks and notations. Because we believe this work is culturally important, we have made it available as part of our commitment for protecting, preserving, and promoting the world's literature in affordable, high quality, modern editions, that are true to their original work.",
    authorName: "J. Allen Boone",
    authorAvatar: "/assets/images/author-10.jpg",
    createdAt: "June 30, 2006",
    cover: "/assets/images/graphic-design-trends-3.png",
  },
  {
    id: 11,
    title: "Props in ReactJS: A Comprehensive Guide",
    category: "development",
    subCategory: ["frontend", "ui/ux", "design"],
    description:
      "When building applications with ReactJS, understanding the concept of “props” is essential. Props, short for “properties,” allow you to pass data from one component to another within your React application. It is a fundamental part of the React architecture and plays a crucial role in creating reusable and dynamic components. In this blog, we’ll explore what props are, how to use them, and best practices for managing them.",
    authorName: "Rahul Agarwal",
    authorAvatar: "/assets/images/author-11.jpg",
    createdAt: "July 30, 2023",
    cover: "/assets/images/designer-7.jpg",
  },
  {
    id: 12,
    title: "Beyond the Bright Sea",
    category: "travel",
    subCategory: ["beaches", "sea", "holidays"],
    description:
      "The moving story of an orphan, determined to know her own history, who discovers the true meaning of family.  Twelve-year-old Crow has lived her entire life on a tiny, isolated piece of the starkly beautiful Elizabeth Islands in Massachusetts. Abandoned and set adrift in a small boat when she was just hours old, Crow’s only companions are Osh, the man who rescued and raised her, and Miss Maggie, their fierce and affectionate neighbor across the sandbar. Crow has always been curious about the world around her, but it isn’t until the night a mysterious fire appears across the water that the unspoken question of her own history forms in her heart. Soon, an unstoppable chain of events is triggered, leading Crow down a path of discovery and danger.Vivid and heart-wrenching, Lauren Wolk’s Beyond the Bright Sea is a gorgeously crafted and tensely paced tale that explores questions of identity, belonging, and the true meaning of family.",
    authorName: " Lauren Wolk ",
    authorAvatar: "/assets/images/author-12.jpg",
    createdAt: "May 02, 2017",
    cover: "/assets/images/beach-3.jpg",
  },
  {
    id: 13,
    title: "ADVENTURE IN YOU",
    category: "adventure",
    subCategory: ["adrenaline", "stay-fit", "lifestyle"],
    description:
      "Are you ready to unlock your inner adventurer and discover new experiences? From hiking and rock climbing to scuba diving and skydiving, there are countless ways to challenge yourself and push beyond your limits. In this article, we'll explore the benefits of adventure travel, from building confidence and resilience to fostering connections and community. We'll also share inspiring stories of people who have embarked on life-changing adventures and provide practical tips and advice for planning your own adventure. So, come and discover the thrill of adventure and the transformative power of exploring the unknown.",
    authorName: "David Kim",
    authorAvatar: "/assets/images/author-13.jpg",
    createdAt: "May 20, 2022",
    cover: "/assets/images/graphic-design-trends-1.png",
  },
  {
    id: 14,
    title: "Passing props to child components in React function components",
    category: "development",
    subCategory: ["frontend", "ui/ux", "design"],
    description:
      "Passing props in React is a fundamental concept that allows data to flow between components. When building user interfaces with React, you often need to pass additional props from a parent component to its child components. This article explores how to pass props to child components, focusing on function components and best practices.",
    authorName: "Łukasz Holeczek",
    authorAvatar: "/assets/images/author-14.jpg",
    createdAt: "October 02, 2024",
    cover: "/assets/images/designer-5.jpg",
  },
  {
    id: 15,
    title: "Loaded BBQ Baked Potatoes",
    category: "cooking",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Oh my, I’ve forgotten how much I love baked potatoes. I’ve been so focused on it’s sweeter cousin, that I completely forgot how comforting and delicious a simple baked potato can be. To take this spud over the top (pun intended), I’ve loaded it with summer flavors: smoky vegetarian baked beans, sharp cheddar, garlicky greens and avocado. Always avocado.These protein-packed potatoes are the perfect lunch or dinner when you’re craving maximum flavor without a lot of effort.",
    authorName: "Alex Caspero",
    authorAvatar: "/assets/images/author-15.jpg",
    createdAt: "May 16, 2016 ",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 16,
    title: "The Rise of Women in Sports",
    category: "sport",
    subCategory: ["athletes", "empowerment", "fitness"],
    description:
      "Women's sports have seen tremendous growth in recent years, breaking records and inspiring a generation. This article explores the journey of female athletes, their challenges, and their triumphs.",
    authorName: "Lunar Press",
    authorAvatar: "/assets/images/author-16.jpg",
    createdAt: "March 27, 2023",
    cover: "/assets/images/sport-1.jpg",
  },
  {
    id: 17,
    title: "Online Shopping – An Alternative to Shopping in the Mall",
    category: "shopping",
    subCategory: ["e-commerce store", "clothing", "shopping store"],
    description:
      "The rise of e-commerce has revolutionized the way we shop. With just a few clicks, you can browse through thousands of products, read reviews, and make purchases from the comfort of your own home. In this article, we'll explore the benefits of online shopping, from convenience and flexibility to cost savings and personalized experiences. We'll also discuss the latest trends and innovations in e-commerce, including AI-powered chatbots, augmented reality, and sustainable packaging. Whether you're a seasoned online shopper or just starting to explore the world of e-commerce, this article will provide you with valuable insights and tips.",
    authorName: "John Paul",
    authorAvatar: "/assets/images/author-9.jpg",
    createdAt: "November 15, 2021",
    cover: "/assets/images/shopping-1.jpg",
  },
  {
    id: 18,
    title: 'Top 10 Iconic Albums of the Decade',
    category: 'music',
    subCategory: ['albums', 'artists', 'trends'],
    description:
      "Music defines generations, and every decade has its unforgettable albums. Dive into the most iconic records of the decade that shaped pop culture and influenced millions.",
    authorName: ' uDiscover Team',
    authorAvatar: '/assets/images/author-13.jpg',
    createdAt: ' December 13, 2019',
    cover: '/assets/images/music-1.jpg',
  },
  {
    id: 19,
    title: "Beyond the Beach",
    category: "travel",
    subCategory: ["beaches", "sea", "holidays"],
    description:
      "Are you ready to venture off the beaten path and explore the unique cultures, stunning landscapes, and exciting activities that lie beyond the beach? From hiking through lush rainforests to exploring vibrant cities and trying local cuisine, there are countless ways to experience the authentic charm of a destination. In this article, we'll take you on a journey to some of the world's most incredible destinations, from the ancient ruins of Machu Picchu to the stunning beaches of Bali. We'll also share practical tips and advice for planning your own off-the-beaten-path adventure. So, come and discover the thrill of exploration and the joy of discovering new experiences.",
    authorName: " Richard D. Stafford",
    authorAvatar: "/assets/images/author-6.jpg",
    createdAt: "May 01, 1999",
    cover: "/assets/images/beach-2.jpg",
  },
  {
    id: 20,
    title: "Art & Perception",
    category: "art",
    subCategory: ["skill", "design", "passion"],
    description:
      "Delve into the fascinating world of art and perception, where creativity meets psychology, and explore the ways in which art shapes our understanding of reality. From the masters of Renaissance art to the innovators of modern and contemporary art, we'll examine the techniques and strategies that artists use to manipulate perception and create new realities. We'll also discuss the latest research in art psychology and neuroscience, and explore the implications of art and perception for our understanding of human consciousness and behavior. Whether you're an art lover, a psychology enthusiast, or simply curious about the human experience, this article will provide you with a unique perspective on the complex and multifaceted relationship between art and perception.",
    authorName: "Sjoerd M. Stuit",
    authorAvatar: "/assets/images/author-20.jpg",
    createdAt: "07 Jan 2025.",
    cover: "/assets/images/art-1.jpg",
  },
  {
    id: 21,
    title: 'The Science of Sports Performance',
    category: 'sport',
    subCategory: ['science', 'training', 'health'],
    description:
      "What does it take to unlock true athletic greatness? In The Science of Sports Performance, renowned sports coach Keith Johnson reveals the physical and mental training secrets that have helped his athletes reach new heights in various sports. Backed by over two decades of working with everyone from struggling high school athletes to Olympians, Johnson breaks down the cutting-edge techniques he uses to optimize sports performance. From central nervous system training to improve mind-body coordination to sport-specific drills that enhance skills and prevent injury, Johnson leaves no stone unturned. The book explores critical topics such as strengthening the mind-body connection through central nervous system training, developing speed and agility, injury prevention strategies, and building sport-specific skills. Johnson also shares inspiring stories of athletes he has coached, highlighting how proper assessment and training can help even the most struggling athletes excel. Blending inspiring stories, science-backed training advice, and clear visual descriptions, The Science of Sports Performance unravels the mysteries of athletic excellence. It is the definitive playbook for pushing physical, mental, and emotional limits to empower athletes to realize their unlimited potential. For any coach, trainer, or athlete seeking the cutting edge of performance, this book is an essential read.",
    authorName: 'Keith Johnson',
    authorAvatar: "/assets/images/author-21.jpg",
    createdAt: "December 29, 2023",
    cover: "/assets/images/sport-3.jpg",
  },
];
